CREATE TABLE CITY (
    ID BIGINT(10) PRIMARY KEY,
    CITY VARCHAR(49),
    CITY_ASCII VARCHAR(49),
    LAT VARCHAR(8),
    LNG VARCHAR(9),
    COUNTRY VARCHAR(45),
    ISO2 VARCHAR(2),
    ISO3 VARCHAR(3),
    ADMIN_NAME VARCHAR(53),
    CAPITAL VARCHAR(7),
    POPULATION BIGINT(10)
);

CREATE INDEX IDX_CITY_CITY
    ON CITY (CITY);

CREATE INDEX IDX_CITY_ASCII_CITY
    ON CITY (CITY_ASCII);
